apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-exercise-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubernetes-exercise-backend
  template:
    metadata:
      labels:
        app: kubernetes-exercise-backend
    spec:
      containers:
        - name: kubernetes-exercise-backend
          image: gatherloop/kubernetes-exercise-backend
          env:
            - name: PORT
              value: "80"
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: kubernetes-exercise
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: kubernetes-exercise
                  key: DB_PORT
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: kubernetes-exercise
                  key: DB_NAME
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: kubernetes-exercise
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kubernetes-exercise
                  key: DB_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: kubernetes-exercise-backend
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: kubernetes-exercise-backend
