apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-exercise-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubernetes-exercise-backend
  template:
    metadata:
      labels:
        app: kubernetes-exercise-backend
    spec:
      containers:
        - name: kubernetes-exercise-backend
          image: gatherloop/kubernetes-exercise-backend
          env:
            - name: PORT
              value: "80"
            - name: DB_HOST
              value: "143.42.79.254"
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              value: "biodata"
            - name: DB_USERNAME
              value: "root"
            - name: DB_PASSWORD
              value: "root"
---
apiVersion: v1
kind: Service
metadata:
  name: kubernetes-exercise-backend
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: kubernetes-exercise-backend
