apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-exercise-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubernetes-exercise-frontend
  template:
    metadata:
      labels:
        app: kubernetes-exercise-frontend
    spec:
      containers:
        - name: kubernetes-exercise-frontend
          image: gatherloop/kubernetes-exercise-frontend
          env:
            - name: PORT
              value: "80"
            - name: API_URL
              value: "https://kubernetes-exercise-api.gatherloop.co"
---
apiVersion: v1
kind: Service
metadata:
  name: kubernetes-exercise-frontend
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: kubernetes-exercise-frontend
