name: cd

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker Login
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: Build Image
        run: |
          docker build -t gatherloop/kubernetes-exercise-frontend:${{ github.sha }} ./frontend
          docker build -t gatherloop/kubernetes-exercise-backend:${{ github.sha }} ./backend
      - name: Push Image
        run: |
          docker push gatherloop/kubernetes-exercise-frontend:${{ github.sha }}
          docker push gatherloop/kubernetes-exercise-backend:${{ github.sha }}
      - name: Kubernetes set context
        uses: Azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG }}
      - name: Kubernetes setup secrets
        run: |
          kubectl create secret generic kubernetes-exercise --from-literal=DB_HOST=${{ secrets.DB_HOST }} --from-literal=DB_NAME=${{ secrets.DB_NAME }} --from-literal=DB_PASSWORD=${{ secrets.DB_PASSWORD }} --from-literal=DB_PORT=${{ secrets.DB_PORT }} --from-literal=DB_USERNAME=${{ secrets.DB_USERNAME }}
      - name: Kubernetes apply
        run: |
          kubectl apply -f k8s/frontend.prod.yml
          kubectl apply -f k8s/backend.prod.yml
          kubectl apply -f k8s/database.prod.yml
          kubectl set image deployment/kubernetes-exercise-frontend kubernetes-exercise-frontend=gatherloop/kubernetes-exercise-frontend:${{ github.sha }}
          kubectl set image deployment/kubernetes-exercise-backend kubernetes-exercise-backend=gatherloop/kubernetes-exercise-backend:${{ github.sha }}
